# Generated by Django 2.2.4 on 2019-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null='', unique=True)),
                ('image_filename', models.CharField(max_length=65, null='')),
                ('image_caption', models.CharField(max_length=410, null='')),
                ('category', models.CharField(max_length=50, null='')),
                ('formula', models.CharField(max_length=280, null='')),
                ('strunz_classification', models.CharField(max_length=110, null='')),
                ('color', models.CharField(max_length=195, null='')),
                ('crystal_system', models.CharField(max_length=130, null='')),
                ('unit_cell', models.CharField(max_length=140, null='')),
                ('crystal_symmetry', models.CharField(max_length=130, null='')),
                ('cleavage', models.CharField(max_length=170, null='')),
                ('mohs_scale_hardness', models.CharField(max_length=70, null='')),
                ('luster', models.CharField(max_length=75, null='')),
                ('streak', models.CharField(max_length=60, null='')),
                ('diaphaneity', models.CharField(max_length=80, null='')),
                ('optical_properties', models.CharField(max_length=85, null='')),
                ('refractive_index', models.CharField(max_length=125, null='')),
                ('crystal_habit', models.CharField(max_length=240, null='')),
                ('specific_gravity', models.CharField(max_length=70, null='')),
                ('group', models.CharField(max_length=20, null='')),
            ],
        ),
    ]
