# Generated by Django 2.2.4 on 2019-08-10 04:49

from django.db import migrations, transaction
from django.db.utils import IntegrityError
import os.path

from ..data.retrieve_json import pull_json

@transaction.atomic
def load_mineral_data(apps, schema_editor):
    
    Mineral = apps.get_model('minerals', 'Mineral')

    mineral_data = pull_json(os.path.abspath('minerals/data/minerals.json'))

    for i, m in enumerate(mineral_data):
        with transaction.atomic():
            try:
                Mineral.objects.create(**m)
            except IntegrityError:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_define_mineral'),
    ]

    operations = [
        migrations.RunPython(load_mineral_data, migrations.RunPython.noop)
    ]
